services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: animals_db

  rails:
    build: ./rails/animals-api
    volumes:
      - ./rails/animals-api:/app
    working_dir: /app
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/animals_db
    depends_on:
      - db
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./cache:/var/cache/nginx
    ports:
      - "80:80"
    depends_on:
      - rails

volumes:
  postgres_data:
