version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
